-- 코드를 입력하세요
SELECT C.CAR_ID AS CAR_ID, C.CAR_TYPE AS CAR_TYPE, FLOOR(C.DAILY_FEE*30*(1-D.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단','SUV') 
AND D.DURATION_TYPE = '30일 이상'
AND C.CAR_ID NOT IN (
    SELECT C.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS R
    JOIN CAR_RENTAL_COMPANY_CAR AS C ON C.CAR_ID = R.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D ON C.CAR_TYPE = D.CAR_TYPE
    WHERE R.START_DATE<='2022-11-30' AND R.END_DATE>='2022-11-01'
)
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;