SELECT ID, 
CASE
    WHEN SIZE_OF_COLONY <= 0.25 THEN 'CRITICAL'
    WHEN SIZE_OF_COLONY <= 0.5 THEN 'HIGH'
    WHEN SIZE_OF_COLONY <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
)AS SUB
ORDER BY ID ASC;