-- 코드를 입력하세요
SELECT YEAR(T.SALES_DATE) AS YEAR, MONTH(T.SALES_DATE) AS MONTH, T.GENDER, COUNT(DISTINCT T.USER_ID) AS USERS
FROM
(
    SELECT O.SALES_DATE, U.GENDER, U.USER_ID
    FROM USER_INFO AS U
    JOIN ONLINE_SALE AS O ON U.USER_ID = O.USER_ID
    WHERE U.GENDER IS NOT NULL
) AS T
GROUP BY YEAR, MONTH, T.GENDER
ORDER BY YEAR ASC, MONTH ASC, T.GENDER ASC;