-- 코드를 입력하세요
SELECT T.USER_ID, T.NICKNAME, SUM(T.PRICE) AS TOTAL_SALES
FROM (
    SELECT *
    FROM USED_GOODS_BOARD AS B 
    JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
    WHERE B.STATUS = 'DONE'
) AS T
GROUP BY T.WRITER_ID
HAVING SUM(T.PRICE)>=700000
ORDER BY TOTAL_SALES ASC;