-- 코드를 입력하세요
SELECT T.CATEGORY, SUM(T.SALES) AS TOTAL_SALES
FROM (
    SELECT B.CATEGORY, B.PRICE, S.SALES
    FROM BOOK AS B
    JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE LIKE '2022-01%'
) AS T
GROUP BY T.CATEGORY
ORDER BY T.CATEGORY ASC;